Practical_Assignment_221519Z/ViewModels/Login.cs
using System.ComponentModel.DataAnnotations;

namespace Practical_Assignment_221519Z.ViewModels
{
	public class Login
	{
		[Required]
		[DataType(DataType.EmailAddress, ErrorMessage = "Invalid email format.")]
		public string Email { get; set; }
		
		[Required]
		[DataType(DataType.Password)]
		public string Password { get; set; }
		public bool RememberMe { get; set; }
    }
}

Practical_Assignment_221519Z/ViewModels/Register.cs
using System.ComponentModel.DataAnnotations;

namespace Practical_Assignment_221519Z.ViewModels
{
    public class Register
    {
        [Required]
		[DataType(DataType.EmailAddress, ErrorMessage = "Invalid email format.")]
		public string Email { get; set; }

        [Required]
        // [DataType(DataType.Password)]
        [MinLength(12, ErrorMessage = "Password Length must be at least 12 characters")]
        [RegularExpression(@"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[$@$!%*?&])[A-Za-z\d$@$!%*?&]{8,}$",
        ErrorMessage = "Passwords must be at least 12 characters long and contain at least an uppercase letter, lower case letter, digit and a special character")]
        public string Password { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Compare(nameof(Password), ErrorMessage = "Password and confirmation password does not match")]
        public string ConfirmPassword { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string FullName { get; set; }


        [Required] // must be encrypted
        [DataType(DataType.CreditCard)]
        public string CreditCardNo { get; set; }


        [Required]
        [DataType(DataType.Text)]
        public string Gender { get; set; }

        [Required]
        [DataType(DataType.PhoneNumber)]
        public string MobileNo { get; set; }


        [Required]
        [DataType(DataType.Text)]
        public string DeliveryAddress { get; set; }



        [Required(ErrorMessage = "Please upload a JPG image.")]
        [RegularExpression(@"^.+\.jpg$", ErrorMessage = "Only JPG files are allowed.")]
        public string Photo { get; set; }


        [Required]
        [RegularExpression(@"^[^\r\n]+$", ErrorMessage = "Special characters are allowed.")]
        public string AboutMe { get; set; }

        
    }
}

Practical_Assignment_221519Z/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Practical_Assignment_221519Z.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

Practical_Assignment_221519Z/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Practical_Assignment_221519Z.Model;

namespace Practical_Assignment_221519Z.Pages
{
    public class IndexModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private SignInManager<ApplicationUser> signInManager { get; }
        public ApplicationUser CurrentUser { get; set; }

        public string CreditCardNo { get; set; }

        public IndexModel(UserManager<ApplicationUser> userManager, SignInManager<ApplicationUser> signInManager)
        {
            this.userManager = userManager;
            this.signInManager = signInManager;
        }

        public async Task ClearSession()
        {
            await signInManager.SignOutAsync();
            HttpContext.Session.Clear();
            var cookies = Request.Cookies.Keys;
            foreach (var cookie in cookies)
            {
                Response.Cookies.Delete(cookie);
            }

            if (Request.Cookies["ASP.NET_SessionId"] != null)
            {
                Response.Cookies.Append("ASP.NET_SessionId", string.Empty, new CookieOptions
                {
                    Expires = DateTime.Now.AddMonths(-20)
                });
            }

            // Clear AuthToken cookie
            if (Request.Cookies["AuthToken"] != null)
            {
                Response.Cookies.Append("AuthToken", string.Empty, new CookieOptions
                {
                    Expires = DateTime.Now.AddMonths(-20)
                });
            }
        }


        public async Task<IActionResult> OnGet()
        {
            var existingAuthToken = HttpContext.Session.GetString("AuthToken");
            if (existingAuthToken != Request.Cookies["AuthToken"])
            {
                // Session is not valid, redirect to the login page
                await ClearSession();
                return RedirectToPage("Login");
            }
            else
            {
                if (signInManager.IsSignedIn(User))
                {
                    CurrentUser = await userManager.GetUserAsync(User);
                    var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                    var protector = dataProtectionProvider.CreateProtector("221519Z_AppSec");
                    CreditCardNo = protector.Unprotect(CurrentUser.CreditCardNo);

                    // Continue with the execution of the page
                    return Page();
                }
            }

            // Session is not valid, redirect to the login page
            await ClearSession();
            return RedirectToPage("Login");
        }



    }
}

Practical_Assignment_221519Z/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Practical_Assignment_221519Z.Model;
using Practical_Assignment_221519Z.ViewModels;
using System.Net;
using System.Text.Json;

namespace Practical_Assignment_221519Z.Pages
{
    public class LoginModel : PageModel
    {
		[BindProperty]
		public Login LModel { get; set; }

		private readonly SignInManager<ApplicationUser> signInManager;
        private AuthDbContext authDbContext { get; }
        public LoginModel(SignInManager<ApplicationUser> signInManager, AuthDbContext authDbContext)
		{
			this.signInManager = signInManager;
            this.authDbContext = authDbContext;
        }
		public void OnGet()
		{
		}

		public class MyObject
		{
			public bool success { get; set; }
		}

		public bool ValidateCaptcha()
		{
			string response = Request.Form["g-recaptcha-response"];

			// Request to Google Server for reCAPTCHA validation
			HttpWebRequest req = (HttpWebRequest)WebRequest.Create($"https://www.google.com/recaptcha/api/siteverify?secret=6LdxT2UpAAAAACIel2VbEsaXpLiCBshAziP5Eysv &response={response}");

			try
			{
				using (WebResponse wResponse = req.GetResponse())
				{
					using (StreamReader readStream = new StreamReader(wResponse.GetResponseStream()))
					{
						string jsonResponse = readStream.ReadToEnd();
						var data = JsonSerializer.Deserialize<MyObject>(jsonResponse);
						return data.success;
					}
				}
			}
			catch (WebException ex)
			{
				throw ex;
			}
		}

        public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                if (HasSqlInjection(LModel.Email))
                {
                    ModelState.AddModelError("", "Invalid characters in the input.");
                    return Page();
                }
                if (!IsValidEmail(LModel.Email))
                {
                    ModelState.AddModelError("", "Invalid email format.");
                    return Page();
                }

                var identityResult = await signInManager.PasswordSignInAsync(LModel.Email, LModel.Password,
                    LModel.RememberMe,lockoutOnFailure: true);
                var isUserLoggedIn = authDbContext.IsUserLoggedIn(LModel.Email);

                if (!isUserLoggedIn)
                {
                    if (identityResult.Succeeded)
                    {
                        // Set session and cookie for successful login
                        
                        HttpContext.Session.SetString("UserId", LModel.Email);
                        string guid = Guid.NewGuid().ToString();
                        HttpContext.Session.SetString("AuthToken", guid);
                        Response.Cookies.Append("AuthToken", guid, new CookieOptions
                        {
                            HttpOnly = true,
                            SameSite = SameSiteMode.Strict,

                        });
                        authDbContext.AddToAuditLog(LModel.Email, "User Logged In");

                        return RedirectToPage("Index");
                    }
                    else if (identityResult.IsLockedOut)
                    {
                        ModelState.AddModelError("", "Account locked out. Try again later.");
                    }
                    else
                    {
                        ModelState.AddModelError("", "Invalid login attempt.");
                    }

                    // reCAPTCHA validation
                    var isCaptchaValid = ValidateCaptcha();
                    if (!isCaptchaValid)
                    {
                        ModelState.AddModelError("", "reCAPTCHA validation failed. Please try again.");
                        return Page();
                    }
                }
                else
                {
                    ModelState.AddModelError("", "Account is logged in on another device.");
                }

                
            }
            return Page();
        }

        private bool IsValidEmail(string email)
        {
            try
            {
                var addr = new System.Net.Mail.MailAddress(email);
                return addr.Address == email;
            }
            catch
            {
                return false;
            }
        }
        private bool HasSqlInjection(string input)
        {
            // Implement SQL injection detection logic
            // Example: Check for common SQL keywords
            string[] sqlKeywords = { "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "CREATE" };
            return sqlKeywords.Any(keyword => input.ToUpper().Contains(keyword));
        }
    }
}

Practical_Assignment_221519Z/Pages/Logout.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Practical_Assignment_221519Z.Model;
using System.Net;

namespace Practical_Assignment_221519Z.Pages
{
    public class LogoutModel : PageModel
    {
		private readonly SignInManager<ApplicationUser> signInManager;
        private AuthDbContext authDbContext { get; }
        public LogoutModel(SignInManager<ApplicationUser> signInManager, AuthDbContext authDbContext)

		{
			this.signInManager = signInManager;
            this.authDbContext = authDbContext;
        }
		public void OnGet()
		{
		}

		public async Task<IActionResult> OnPostLogoutAsync()
		{
			await signInManager.SignOutAsync();
			HttpContext.Session.Clear();
			var cookies = Request.Cookies.Keys;
			foreach (var cookie in cookies)
			{
				Response.Cookies.Delete(cookie);
			}

			if (Request.Cookies["ASP.NET_SessionId"] != null)
			{
				Response.Cookies.Append("ASP.NET_SessionId", string.Empty, new CookieOptions
				{
					Expires = DateTime.Now.AddMonths(-20)
				});
			}

			// Clear AuthToken cookie
			if (Request.Cookies["AuthToken"] != null)
			{
				Response.Cookies.Append("AuthToken", string.Empty, new CookieOptions
				{
					Expires = DateTime.Now.AddMonths(-20)
				});
			}

            authDbContext.AddToAuditLog(User.Identity.Name, "User Logged Out");
            return RedirectToPage("Login");
		}
		public async Task<IActionResult> OnPostDontLogoutAsync()
		{
			return RedirectToPage("Index");
		}
	}
}

Practical_Assignment_221519Z/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Practical_Assignment_221519Z.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

Practical_Assignment_221519Z/Pages/Register.cshtml.cs
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Practical_Assignment_221519Z.Model;
using Practical_Assignment_221519Z.ViewModels;
using System.Net;
using System.Text.Json;


namespace Practical_Assignment_221519Z.Pages
{
    public class RegisterModel : PageModel
    {
        private UserManager<ApplicationUser> userManager { get; }
        private SignInManager<ApplicationUser> signInManager { get; }
        private AuthDbContext authDbContext { get; }


        [BindProperty]
        public Register RModel { get; set; }

        public RegisterModel(UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager,
        AuthDbContext authDbContext
        )

        {
            this.userManager = userManager;
            this.signInManager = signInManager;
            this.authDbContext = authDbContext;
        }

        public void OnGet()
        {
        }

        public class MyObject
        {
            public bool success { get; set; }
        }

        public bool ValidateCaptcha()
        {
            string response = Request.Form["g-recaptcha-response"];

            // Request to Google Server for reCAPTCHA validation
            HttpWebRequest req = (HttpWebRequest)WebRequest.Create($"https://www.google.com/recaptcha/api/siteverify?secret=6LdxT2UpAAAAACIel2VbEsaXpLiCBshAziP5Eysv &response={response}");

            try
            {
                using (WebResponse wResponse = req.GetResponse())
                {
                    using (StreamReader readStream = new StreamReader(wResponse.GetResponseStream()))
                    {
                        string jsonResponse = readStream.ReadToEnd();
                        var data = JsonSerializer.Deserialize<MyObject>(jsonResponse);
                        return data.success;
                    }
                }
            }
            catch (WebException ex)
            {
                throw ex;
            }
        }


        private bool HasSqlInjection(string input)
        {
            // Implement SQL injection detection logic
            // Example: Check for common SQL keywords
            string[] sqlKeywords = { "SELECT", "INSERT", "UPDATE", "DELETE", "DROP", "CREATE" };
            return sqlKeywords.Any(keyword => input.ToUpper().Contains(keyword));
        }

		private bool IsValidEmail(string email)
		{
			try
			{
				var addr = new System.Net.Mail.MailAddress(email);
				return addr.Address == email;
			}
			catch
			{
				return false;
			}
		}

		public async Task<IActionResult> OnPostAsync()
        {
            if (ModelState.IsValid)
            {
                // Encryption
                var dataProtectionProvider = DataProtectionProvider.Create("EncryptData");
                var protector = dataProtectionProvider.CreateProtector("221519Z_AppSec");
                
                var user = new ApplicationUser()
					{
						UserName = WebUtility.HtmlEncode(RModel.Email),
						Email = WebUtility.HtmlEncode(RModel.Email),
						FullName = WebUtility.HtmlEncode(RModel.FullName),
				        CreditCardNo = WebUtility.HtmlEncode(protector.Protect(RModel.CreditCardNo)),
						Gender = WebUtility.HtmlEncode(RModel.Gender),
						MobileNo = WebUtility.HtmlEncode(RModel.MobileNo),
						DeliveryAddress = WebUtility.HtmlEncode(RModel.DeliveryAddress),
						Photo = WebUtility.HtmlEncode(RModel.Photo),
						AboutMe = WebUtility.HtmlEncode(RModel.AboutMe),
					};
                

                if (HasSqlInjection(RModel.Email))
                {
                    ModelState.AddModelError("", "Invalid characters in the input.");
                   return Page();
                }
                if (!IsValidEmail(RModel.Email))
                {
                    ModelState.AddModelError("", "Invalid email format.");
                    return Page();
                }
                var result = await userManager.CreateAsync(user, RModel.Password);
                if (result.Succeeded)
					{
                    authDbContext.AddToAuditLog(user.UserName, "User Registered");
                    return RedirectToPage("Login");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error.Description);
					}
                    var isCaptchaValid = ValidateCaptcha();
                    if (!isCaptchaValid)
                    {
                        ModelState.AddModelError("", "reCAPTCHA validation failed. Please try again.");
                        return Page();
                    }


            }
            return Page();
        }
    }
}

Practical_Assignment_221519Z/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="row justify-content-center align-items-center">
    <h1 class="display-4">Customer Data:</h1>
    @if (Model.CurrentUser != null)
    {
        <p>Full Name: @Html.DisplayFor(m => m.CurrentUser.FullName)</p>
        <p>Credit Card No: @Html.DisplayFor(m => m.CreditCardNo)</p>
        <p>Gender: @Html.DisplayFor(m => m.CurrentUser.Gender)</p>
        <p>Delivery Address: @Html.DisplayFor(m => m.CurrentUser.DeliveryAddress)</p>
        <p>Email Address: @Html.DisplayFor(m => m.CurrentUser.Email)</p>
        <p>Photo: @Html.DisplayFor(m => m.CurrentUser.Photo)</p>
        <p>About Me: @Html.DisplayFor(m => m.CurrentUser.AboutMe)</p>
    }
    else
    {
        <p>User not found.</p>
    }
</div>

<script>
    var sessionTimeoutInSeconds = 30;

    var timer = setTimeout(function () {
        var encodedMessage = "You have been idle for the last 30 seconds. You will now be logged out of your account.";
        window.location.reload();
        alert(encodedMessage);
    }, sessionTimeoutInSeconds * 1000); // Alert after 30 seconds of inactivity
</script>

Practical_Assignment_221519Z/Pages/Login.cshtml
@page
@model Practical_Assignment_221519Z.Pages.LoginModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Login </h1>

			<form method="post" id="loginForm">
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Email">Email Address</label>
					<input type="Text" asp-for="LModel.Email" class="form-control" />
					<span asp-validaton-for="LModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="LModel.Password">Password</label>
					<input type="password" asp-for="LModel.Password" class="form-control" />
					<span asp-validaton-for="LModel.Password" class="text-danger"></span>
				</div>

				<div class="mb-3 form-check">
					<input type="checkbox" asp-for="LModel.RememberMe" class="form-check-input" />
					<label class="form-check-label" asp-for="LModel.RememberMe">Remember Me?</label>
				</div>

				<div class="mb-3">
					<button class="g-recaptcha"
							data-sitekey="6LdxT2UpAAAAAJpNkS65GLEa1pA5Y5rTbaepiJL4"
							data-callback='onSubmit'
							data-action='submit'>
						Login
					</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script src="https://google.com/recaptcha/api.js"></script>
<script>
	function onSubmit(token) {
		document.getElementById("loginForm").submit();
	}
</script>

Practical_Assignment_221519Z/Pages/Logout.cshtml
@page
@model Practical_Assignment_221519Z.Pages.LogoutModel
@{
}
<form method="post">
	<div class="container mt-5">
		<div class="row justify-content-center">
			<div class="col-sm-12 col-md-12 col-lg-4">
				<p> Are you sure you want to logout? </p>
				<p>
					<button class="btn btn-primary" asp-page-handler="Logout">Yes</button>
					<button class="btn btn-light ml-5 border-dark" asp-page-handler="DontLogout">No</button>
				</p>
			</div>
		</div>
	</div>
</form>

Practical_Assignment_221519Z/Pages/Register.cshtml
@page
@model Practical_Assignment_221519Z.Pages.RegisterModel
@{
}
<div class="container mt-5">

	<div class="row justify-content-center align-items-center">

		<div class="col-sm-12 col-md-12 col-lg-4">
			<h1 class="mb-3">Register </h1>

			<form method="post" id="registrationForm">
				@Html.AntiForgeryToken()
				<div asp-validation-summary="All" class="text-danger"></div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Email">Email Address</label>
					<input type="email" asp-for="RModel.Email" class="form-control" />
					<span asp-validation-for="RModel.Email" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Password">Password</label>
					<input type="password" asp-for="RModel.Password" class="form-control" id="password" onkeyup="validate()"/>
					<span asp-validation-for="RModel.Password" class="text-danger"></span>
					<div id="pwdchecker"></div>
					<div id="passwordStrength"></div>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.ConfirmPassword">Confirm Password</label>
					<input type="password" asp-for="RModel.ConfirmPassword" class="form-control" />
					<span asp-validation-for="RModel.ConfirmPassword" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.FullName">Full Name</label>
					<input type="Text" asp-for="RModel.FullName" class="form-control" />
					<span asp-validation-for="RModel.FullName" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.CreditCardNo">Credit Card No</label>
					<input type="text" maxlength="16" asp-for="RModel.CreditCardNo" class="form-control" />
					<span asp-validation-for="RModel.CreditCardNo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Gender">Gender</label>
					<input type="Text" asp-for="RModel.Gender" class="form-control" />
					<span asp-validation-for="RModel.Gender" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.MobileNo">Mobile No</label>
					<input type="tel" asp-for="RModel.MobileNo" class="form-control" />
					<span asp-validation-for="RModel.MobileNo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.DeliveryAddress">Delivery Address</label>
					<input type="Text" asp-for="RModel.DeliveryAddress" class="form-control" />
					<span asp-validation-for="RModel.DeliveryAddress" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.Photo">Photo</label>
					<input type="file" asp-for="RModel.Photo" class="form-control" />
					<span asp-validation-for="RModel.Photo" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<label class="form-label" asp-for="RModel.AboutMe">About Me</label>
					<textarea type="text" asp-for="RModel.AboutMe" class="form-control"></textarea>
					<span asp-validation-for="RModel.AboutMe" class="text-danger"></span>
				</div>

				<div class="mb-3">
					<button class="g-recaptcha"
							data-sitekey="6LdxT2UpAAAAAJpNkS65GLEa1pA5Y5rTbaepiJL4"
							data-callback='onSubmit'
							data-action='submit'>
						Register
					</button>
				</div>
			</form>
		</div>
	</div>
</div>

<script>
	function validate() {
		var password = document.getElementById('password').value;
		if (password.length < 12) {
			document.getElementById("pwdchecker").innerHTML = "Password Length must be at least 12 characters";
			document.getElementById("pwdchecker").style.color = "Red";
			return "too_short";
		} else if (password.search(/[0-9]/) === -1) {
			document.getElementById("pwdchecker").innerHTML = "Password requires at least 1 number";
			document.getElementById("pwdchecker").style.color = "Red";
			return "no_number";
		} else if (password.search(/[a-z]/) === -1) {
			document.getElementById("pwdchecker").innerHTML = "Password requires at least 1 lowercase letter";
			document.getElementById("pwdchecker").style.color = "Red";
			return "no_lower_case";
		} else if (password.search(/[A-Z]/) === -1) {
			document.getElementById("pwdchecker").innerHTML = "Password requires at least 1 uppercase letter";
			document.getElementById("pwdchecker").style.color = "Red";
			return "no_uppercase_case";
		} else if (password.search(/[^a-zA-Z0-9]/) === -1) {
			document.getElementById("pwdchecker").innerHTML = "Password requires at least 1 special character";
			document.getElementById("pwdchecker").style.color = "Red";
			return "no_special_character";
		} else {
			document.getElementById("pwdchecker").innerHTML = "Excellent!";
			document.getElementById("pwdchecker").style.color = "Blue";
			var feedbackElement = document.getElementById('passwordStrength');
			feedbackElement.innerHTML = 'STRONG Password';
		}
		
	}

</script>
<script src="https://google.com/recaptcha/api.js"></script>
<script>
	function onSubmit(token) {
		document.getElementById("registrationForm").submit();
	}
</script>